Repository FRONTENDSCHOOL10/8lo8lome, pull requests merged in 2024-09, with the labels that each got.

#17 [설정] 환경설정 및 회웝가입 기능 구현
  public/assets/bg.avif
  public/assets/checked.svg
  public/assets/logo.svg
  public/assets/unchecked.svg
  src/components/AppAuthMessage.jsx
  src/components/AppButton.jsx
  src/components/AppDivider.jsx
  src/components/AppHeader.jsx
  src/components/AppInput.jsx
  src/components/index.js
  src/layouts/RootLayout.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Fallback.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Login/FindId.jsx
  src/pages/Login/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/health.jsx
  src/pages/Main/health/health.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/Signup.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/store.js
  src/router.jsx
  tailwind.config.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS, 🏗️ Environment, 🛠️ Refactor

#21 [기능] svg파일 추가
  public/assets/sprite.svg
Labels: 🦴 Markup

#22 [기능] 회원가입
  src/api/axios.js
  src/components/AppButton.jsx
  src/components/AppDivider.jsx
  src/components/AppInput.jsx
  src/pages/Signup/Age.jsx
  src/pages/Signup/AgreementTerms.jsx
  src/pages/Signup/Email.jsx
  src/pages/Signup/Gender.jsx
  src/pages/Signup/Nickname.jsx
  src/pages/Signup/Password.jsx
  src/pages/Signup/PasswordConfirm.jsx
  src/pages/Signup/PhoneNumber.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/store.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🎀 CSS, 🛠️ Refactor

#25 [기능] 로그인
  src/components/AppInput.jsx
  src/layouts/RootLayout.jsx
  src/main.jsx
  src/pages/Login/AuthLinks.jsx
  src/pages/Login/Email.jsx
  src/pages/Login/FindId/FindId.jsx
  src/pages/Login/FindPassword/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Password.jsx
  src/pages/Login/store.js
  src/router.jsx
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#27 [기능] 회원가입
  public/assets/sprite.svg
  src/api/axios.js
  src/components/AppAuthMessage.jsx
  src/components/AppInput.jsx
  src/constant.js
  src/pages/Signup/AgreementTerms.jsx
  src/pages/Signup/Email.jsx
  src/pages/Signup/Nickname.jsx
  src/pages/Signup/Password.jsx
  src/pages/Signup/PasswordConfirm.jsx
  src/pages/Signup/PhoneNumber.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/store.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#29 [마크업/스타일링]메인페이지
  src/pages/Main/Gym.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map.jsx
  src/pages/Main/health.jsx
  src/router.jsx
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#28 [마크업/스타일링]마이페이지
  package.json
  pnpm-lock.yaml
  src/pages/MyPage/Header.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/Profile.jsx
  tailwind.config.js
Labels: 🦴 Markup, 🎀 CSS

#31 [수정] AppInput 수정
  public/assets/checked.svg
  public/assets/unchecked.svg
  src/api/axios.js
  src/components/AppInput.jsx
  src/pages/Signup/AgreementTerms.jsx
  src/pages/Signup/store.js
Labels: ⚛️ React, 🎗️ Javascript, 🛠️ Refactor

#34 [생성] AppInput 컴포넌트 세부화
  src/components/AppButton.jsx
  src/components/AppCheckboxInput.jsx
  src/components/AppEmailInput.jsx
  src/components/AppPasswordInput.jsx
  src/components/AppRadioInput.jsx
  src/components/AppTextInput.jsx
  src/components/index.js
  src/pages/Home.jsx
  src/pages/Login/Email.jsx
  src/pages/Login/FindId/EmailDisplay.jsx
  src/pages/Login/FindId/FindId.jsx
  src/pages/Login/FindId/PhoneNumberInput.jsx
  src/pages/Login/FindId/VerificationCodeInput.jsx
  src/pages/Login/FindId/findStore.js
  src/pages/Login/Login.jsx
  src/pages/Login/Password.jsx
  src/pages/Login/loginStore.js
  src/pages/Main/Main.jsx
  src/pages/Signup/Age.jsx
  src/pages/Signup/AgreementTerms.jsx
  src/pages/Signup/Email.jsx
  src/pages/Signup/Gender.jsx
  src/pages/Signup/Nickname.jsx
  src/pages/Signup/Password.jsx
  src/pages/Signup/PasswordConfirm.jsx
  src/pages/Signup/PhoneNumber.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/signStore.js
  tailwind.config.js
Labels: ⚛️ React, 🛠️ Refactor

#35 [마크업/스타일링] 마이페이지
  src/pages/MyPage/Profile.jsx
  tailwind.config.js
Labels: 🦴 Markup, 🎀 CSS

#39 [설정] 환경설정
  index.html
  manifest.webmanifest
  src/api/CRUD.js
  src/components/AppAuthMessage.jsx
  src/components/AppButton.jsx
  src/components/AppCheckboxInput.jsx
  src/components/AppDivider.jsx
  src/components/AppEmailInput.jsx
  src/components/AppFooter.jsx
  src/components/AppForm.jsx
  src/components/AppHeader.jsx
  src/components/AppInput.jsx
  src/components/AppMeta.jsx
  src/components/AppNav.jsx
  src/components/AppNavLink.jsx
  src/components/AppPasswordInput.jsx
  src/components/AppRadioInput.jsx
  src/components/AppTextInput.jsx
  src/layouts/RootLayout.jsx
  src/pages/Error.jsx
  src/pages/Fallback.jsx
  src/pages/Home.jsx
  src/pages/Login/AuthLinks.jsx
  src/pages/Login/Email.jsx
  src/pages/Login/FindId/EmailDisplay.jsx
  src/pages/Login/FindId/FindId.jsx
  src/pages/Login/FindId/PhoneNumberInput.jsx
  src/pages/Login/FindId/findStore.js
  src/pages/Login/FindPassword/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/MyPage/Header.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/Profile.jsx
  src/pages/Signup/Age.jsx
  src/pages/Signup/AgreementTerms.jsx
  src/pages/Signup/Gender.jsx
  src/pages/Signup/PhoneNumber.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/signStore.js
  src/styles/main.css
  tailwind.config.js
Labels: 🦴 Markup, ⚛️ React, 👻 Pocketbase, 🏗️ Environment, 🛠️ Refactor

#40 [생성] logo.svg
  public/assets/logo.svg
Labels: 🐞 Bug, 🛠️ Refactor

#42 [수정] router.jsx lazy-loading 수정
  index.html
  src/components/AppMeta.jsx
  src/router.jsx
Labels: ⚛️ React, 🛠️ Refactor

#44 [마크업/스타일] 마이 페이지
  public/assets/sprite.svg
  src/App.jsx
  src/components/AppLoading.jsx
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#45 [기능] 회원가입시 동일한 전화번호로 가입 불가 기능 추가
  src/pages/Signup/PhoneNumber.jsx
  src/pages/Signup/signStore.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#46 [추가/ 삭제]
  public/assets/sprite.svg
  src/App.jsx
Labels: ⚛️ React, 🎗️ Javascript, 🎀 CSS

#49 [수정/삭제] 마이페이지, tailwind
  public/assets/sprite.svg
  src/App.jsx
  src/pages/MyPage/Header.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/MyPage.jsx
  tailwind.config.js
Labels: 🦴 Markup, ⚛️ React, 🎀 CSS

#51 [마크업/스타일링]메인페이지
  src/pages/Main/Gym.jsx
  src/pages/Main/Gym/Gym.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/MapLink.jsx
  src/pages/Main/SearchBar.jsx
  src/router.jsx
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#52 [수정/ 에러]
  src/pages/MyPage/EditProfile/EditProfile.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyProfile.jsx
  src/router.jsx
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS, 🛠️ Refactor

#54 [수정] EditProfile 라우터 경로 수정
  src/pages/MyPage/EditProfile/EditProfile.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyProfile.jsx
  src/router.jsx
Labels: ⚛️ React

#56 [수정] AppMeta import 경로 수정
  src/pages/MyPage/EditProfile/EditProfile.jsx
Labels: 🐞 Bug

#58 [수정] 전반적인 디자인 레이아웃 수정
  src/components/AppHeader.jsx
  src/layouts/RootLayout.jsx
  src/pages/Home.jsx
  src/pages/Login/FindId/FindId.jsx
  src/pages/Login/FindPassword/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/MyPage/EditProfile/EditProfile.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/Signup/Age.jsx
Labels: 🎀 CSS

#66 [수정] CRUD 코드 수정
  src/api/CRUD.js
  src/components/AppSuccess.jsx
  src/pages/Home.jsx
  src/router.jsx
  src/stores/findIdStore.js
  src/stores/findPasswordStore.js
  src/stores/signStore.js
Labels: 👻 Pocketbase

#69 [수정/생성] AppNav 포지션 고정 및 RootLayout 스크롤 안보임 설정
  src/components/AppNav.jsx
  src/layouts/RootLayout.jsx
  src/pages/Chat/Chat.jsx
  src/router.jsx
  src/styles/_scroll.css
  src/styles/main.css
  src/utils/getNavigationItems.js
Labels: 🎀 CSS, 🛠️ Refactor

#72 Feature/chat
  src/components/AppHeader.jsx
  src/components/AppNav.jsx
  src/components/AppStatusPage.jsx
  src/stores/signStore.js
Labels: ⚛️ React, 🎀 CSS, 🛠️ Refactor

#74 [수정] Appsucess 이름 변경 (빌드 오류 수정)
  src/components/AppStatusPage.jsx
  src/router.jsx
Labels: 🐞 Bug

#77 [마크업/스타일링/기능] 메인페이지,지도,필터
  src/pages/Main/Filter/Filter.jsx
  src/pages/Main/Filter/star.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/SearchBar.jsx
  src/stores/mainStore.js
  src/utils/throttle.js
Labels: 🐞 Bug

#79 [마크업/ 스타일링/기능] MyPage-MyProfile
  src/pages/MyPage/EditProfile/EditProfile.jsx
  src/pages/MyPage/LogOut/LogOut.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyProfile.jsx
  src/pages/MyPage/PaymentHistory/PaymentHistory.jsx
  src/pages/MyPage/ReviewSettings/ReviewSettings.jsx
  src/pages/MyPage/Setting/Setting.jsx
  src/pages/MyPage/WishList/WishList.jsx
  src/router.jsx
  src/utils/getPbImageURL.js
  src/utils/index.js
  src/utils/raiseValue.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#78 [수정] 빌드 오류
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
Labels: 🐞 Bug

#81 [수정] router.jsx 이슈 해결
  src/components/AppStatusPage.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/LoggedIn.jsx
  src/pages/Chat/LoggedOut.jsx
  src/router.jsx
  src/stores/chatStore.js
Labels: 🐞 Bug

#82 [수정] getPbImageURL 코드 수정 및 적용
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/SearchBar.jsx
  src/pages/MyPage/MyProfile.jsx
  src/utils/getPbImageURL.js
Labels: 🎗️ Javascript, 👻 Pocketbase

#84 [수정] 필요없는 코드 삭제, gymList 스타일 수정
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/SearchBar.jsx
Labels: ⚛️ React, 🎗️ Javascript, 🎀 CSS

#86 [수정] router / GymList에서 params로 id값 전달 / gym -> gymDetail 변경
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Main/GymList.jsx
  src/router.jsx
Labels: ⚛️ React, 🛠️ Refactor

#87 [수정/마크업/기능] 메인페이지/지도 렌더링, 코드 리뷰 반영, 필터 기능, 메인스토어 렌더링 이슈
  src/components/AppCheckboxInput.jsx
  src/pages/Main/Filter/AgeGroup.jsx
  src/pages/Main/Filter/Amenities.jsx
  src/pages/Main/Filter/Counselor.jsx
  src/pages/Main/Filter/Filter.jsx
  src/pages/Main/Filter/HealthPrice.jsx
  src/pages/Main/Filter/PtPrice.jsx
  src/pages/Main/Filter/Rating.jsx
  src/pages/Main/Filter/TrainerCount.jsx
  src/pages/Main/Filter/TrainerInfo.jsx
  src/pages/Main/Filter/star.jsx
  src/pages/Main/FilterList.jsx
  src/pages/Main/Gym/Gym.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/SearchBar.jsx
  src/stores/mainStore.js
  src/utils/throttle.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🛠️ Refactor

#88 [수정/마크업/생성] EditProfile/ Logout
  src/pages/MyPage/EditProfile/EditEmail.jsx
  src/pages/MyPage/EditProfile/EditImage.jsx
  src/pages/MyPage/EditProfile/EditNickname.jsx
  src/pages/MyPage/EditProfile/EditNumber.jsx
  src/pages/MyPage/EditProfile/EditProfile.jsx
  src/pages/MyPage/LogOut/LogOut.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyProfile.jsx
  src/stores/myPageStore.js
Labels: 🦴 Markup, 🎗️ Javascript, 🎀 CSS

#89 [마크업/스타일링/기능] 채팅 리스트 페이지
  src/api/CRUD.js
  src/components/AppHeader.jsx
  src/components/AppNav.jsx
  src/components/AppStatusPage.jsx
  src/layouts/RootLayout.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatMessages.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/ChatRoomList.jsx
  src/pages/Chat/LoggedIn.jsx
  src/pages/Chat/LoggedOut.jsx
  src/pages/Chat/Logout.jsx
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Signup/Signup.jsx
  src/stores/chatStore.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🎀 CSS, 🛠️ Refactor

#90 [기능] react-swipeable을 사용하여 채팅방 삭제 기능 구현
  package.json
  pnpm-lock.yaml
  src/components/AppFooter.jsx
  src/components/AppForm.jsx
  src/components/AppStatusPage.jsx
  src/components/AppSwitch.jsx
  src/components/index.js
  src/hooks/useClock.js
  src/hooks/useCounter.js
  src/hooks/useDocumentTitle.js
  src/hooks/useEventListener.js
  src/hooks/useFetch.js
  src/hooks/useInView.js
  src/hooks/useLocalStorage.js
  src/hooks/useMousePosition.js
  src/hooks/useOnline.js
  src/hooks/useRenderCount.js
  src/hooks/useRenderCountLog.js
  src/hooks/useSessionStorage.js
  src/hooks/useStateWithCallback.js
  src/hooks/useToggle.js
  src/pages/Chat/ChatMessages.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/ChatRoomList.jsx
  src/pages/Chat/ChatSubmitForm.jsx
  src/pages/Chat/SwipeableChatRoom.jsx
  src/pages/Login/AuthLinks.jsx
  src/pages/Login/Login.jsx
  src/stores/chatStore.js
  src/utils/delay.js
  src/utils/formatTime.js
  src/utils/index.js
  src/utils/protectedLoader.js
  src/utils/raiseValue.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🏗️ Environment, 🛠️ Refactor

#92 [기능] 채팅 실시간 구독서비스 버그 해결
  src/pages/Chat/ChatMessages.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/SwipeableChatRoom.jsx
  src/stores/chatStore.js
Labels: 🐞 Bug, ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#93 [마크업/스타일링] LogOut/Settimg
  package.json
  pnpm-lock.yaml
  src/pages/MyPage/EditProfile/EditImage.jsx
  src/pages/MyPage/LogOut/LogOut.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyProfile.jsx
  src/pages/MyPage/Setting/Setting.jsx
  src/pages/MyPage/Setting/SingOut.jsx
Labels: 🦴 Markup, 🎗️ Javascript, 🎀 CSS

#94 [마크업/스타일링/기능] 메인페이지/ 짐 디테일 마크업, db 가져오는 함수
  src/pages/Main/Filter/Rating.jsx
  src/pages/Main/GymDetail/GymDetail.jsx
  src/stores/mainStore.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#96 [수정] 전반적인 디자인 레이아웃 수정 및 피드백 받은 내용 수정 Feature/chat
  package.json
  src/components/AppHeader.jsx
  src/components/AppLoading.jsx
  src/components/AppNav.jsx
  src/components/AppRadioInput.jsx
  src/components/AppStatusPage.jsx
  src/layouts/RootLayout.jsx
  src/pages/Chat/ChatSubmitForm.jsx
  src/pages/Chat/SwipeableChatRoom.jsx
  src/pages/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Signup/Age.jsx
  src/pages/Signup/AgreementTerms.jsx
  src/pages/Signup/Email.jsx
  src/pages/Signup/Gender.jsx
  src/pages/Signup/Nickname.jsx
  src/pages/Signup/Password.jsx
  src/pages/Signup/PasswordConfirm.jsx
  src/pages/Signup/PhoneNumber.jsx
  src/pages/Signup/Signup.jsx
  src/router.jsx
Labels: 🎀 CSS, 🏗️ Environment, 🛠️ Refactor

#97 [수정] 메인페이지/ 2차 멘토링 내용 반영
  package.json
  src/pages/Main/GymList.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/MapLink.jsx
  src/stores/mainStore.js
Labels: 🛠️ Refactor

#98 [2차 피드백 반영/ 이미지 파일 추가]Public-image
  public/image/logo dark.png
  public/image/success.png
  public/image/결제 완료.png
  public/image/로그인.png
  public/image/탈퇴.png
  src/pages/MyPage/LogOut/LogOut.jsx
  src/pages/MyPage/MyProfile.jsx
  src/pages/MyPage/Setting/Setting.jsx
Labels: 🦴 Markup, 🎀 CSS, 🏗️ Environment

#99 [추가] assets 이모지 svg추가
  public/assets/logoL.png
  public/assets/logoM.png
  public/assets/logoS.png
  public/assets/logout.svg
  public/assets/pleaseLogin.svg
  public/assets/탈퇴.svg
  public/image/logo dark.png
  public/image/success.png
  public/image/결제 완료.png
  public/image/로그인.png
  public/image/탈퇴.png
  src/pages/MyPage/LogOut/LogOut.jsx
Labels: 🏗️ Environment

#101 [수정] AppStatusPage 코드 리팩토링
  index.html
  manifest.webmanifest
  public/assets/imojiSprite.png
  public/assets/logo.png
  public/assets/logo.svg
  public/assets/logoL.png
  public/assets/logoM.png
  public/assets/logoS.png
  public/assets/logout.svg
  public/assets/pleaseLogin.svg
  public/assets/탈퇴.svg
  public/manifest.webmanifest
  src/components/AppAuthMessage.jsx
  src/components/AppDivider.jsx
  src/components/AppLoading.jsx
  src/components/AppNav.jsx
  src/components/AppSpinner.jsx
  src/components/AppStatusPage.jsx
  src/layouts/RootLayout.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoomList.jsx
  src/pages/Chat/Logout.jsx
  src/pages/Chat/NotLogin.jsx
  src/pages/Home.jsx
  src/pages/Login/AuthLinks.jsx
  src/pages/Login/FindPassword/FindPassword.jsx
  src/pages/Signup/Email.jsx
  src/pages/Signup/Nickname.jsx
  src/pages/Signup/Password.jsx
  src/pages/Signup/PasswordConfirm.jsx
  tailwind.config.js
Labels: ⚛️ React, 🛠️ Refactor

#106 [기능] 채팅방 이름 가져오기 기능 수정
  src/components/index.js
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/SwipeableChatRoom.jsx
  src/stores/chatStore.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#107 [기능] 대화 삭제 기능 구현
  src/pages/Chat/ChatMessages.jsx
  src/pages/Chat/ChatRoomList.jsx
  src/pages/Chat/SwipeableChatRoom.jsx
  src/pages/Chat/SwipeableMessage.jsx
  src/stores/chatStore.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#108 [마크업/스타일링/수정] 메인, 필터, 디테일 페이지/ 마크업, 스타일링, tailwind 변수 추가
  src/components/AppCheckboxInput.jsx
  src/pages/Main/Filter/AgeGroup.jsx
  src/pages/Main/Filter/Amenities.jsx
  src/pages/Main/Filter/Counselor.jsx
  src/pages/Main/Filter/Filter.jsx
  src/pages/Main/Filter/HealthPrice.jsx
  src/pages/Main/Filter/PtPrice.jsx
  src/pages/Main/Filter/Rating.jsx
  src/pages/Main/Filter/TrainerCount.jsx
  src/pages/Main/Filter/TrainerInfo.jsx
  src/pages/Main/FilterLink.jsx
  src/pages/Main/FilterList.jsx
  src/pages/Main/GymDetail/AmenitiesList.jsx
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/GymDetailHeader.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/GymDetail/PriceList.jsx
  src/pages/Main/GymDetail/Refundpolicy.jsx
  src/pages/Main/GymDetail/ReviewLink.jsx
  src/pages/Main/GymDetail/TrainerList.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MapLink.jsx
  src/pages/Main/SearchBar.jsx
  src/stores/mainStore.js
  tailwind.config.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#109 [마크업/수정] 헬스장 리뷰 페이지 라우터 추가, 별점 컴포넌트 생성
  src/components/AppRating.jsx
  src/components/index.js
  src/pages/Main/GymDetail/GymDetailHeader.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Review/Review.jsx
  src/router.jsx
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#111 [기능] 헬스장 필터기능 (별점 / 이용권금액 / pt금액 / 편의시설)
  src/components/AppCheckboxInput.jsx
  src/components/AppRating.jsx
  src/pages/Main/Filter/Amenities.jsx
  src/pages/Main/Filter/Filter.jsx
  src/pages/Main/Filter/HealthPrice.jsx
  src/pages/Main/Filter/PtPrice.jsx
  src/pages/Main/Filter/Rating.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/stores/mainStore.js
  tailwind.config.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#113 [기능] 선택된 필터가 필터 리스트에 나오게 구현
  src/pages/Main/Filter/Amenities.jsx
  src/pages/Main/Filter/HealthPrice.jsx
  src/pages/Main/Filter/PtPrice.jsx
  src/pages/Main/FilterList.jsx
  src/pages/Main/GymList.jsx
  src/stores/mainStore.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#115 [기능] map.jsx 카카오 지도 api를 이용한 내 위치를 기반으로 한 헬스장 정보 노출 기능
  index.html
  src/pages/Main/Map/Map.jsx
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#116 [기능]MyPage/logOurStore 로그아웃 기능 오류
  src/pages/MyPage/EditProfile/EditNickname.jsx
  src/pages/MyPage/LogOut/LogOut.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/Setting/Setting.jsx
  src/pages/MyPage/Setting/SingOut.jsx
  src/router.jsx
  src/stores/logOutStore.js
  src/stores/myPageStore.js
Labels: 🐞 Bug, 🦴 Markup, ⚛️ React, 🎗️ Javascript

#118 [수정] 로그아웃시 발생하는 오류 해결
  src/components/AppStatusPage.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyPage.jsx
  src/stores/deleteIdStore.js
  src/stores/logOutStore.js
Labels: 🐞 Bug, ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#119 [마크업/스타일링] 헬스장 디테일 페이지 마크업, 스타일링
  src/pages/Main/GymDetail/AmenitiesList.jsx
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/GymDetailHeader.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/GymDetail/PriceList.jsx
  src/pages/Main/GymDetail/Refundpolicy.jsx
  src/pages/Main/GymDetail/ReviewLink.jsx
  src/pages/Main/GymDetail/TrainerList.jsx
  src/stores/mainStore.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#121 [기능] 헬스장 정보들을 가져와서 경도와 위도를 구한 후 마커찍기
  src/components/AppStatusPage.jsx
  src/pages/Main/Map/Map.jsx
  src/stores/findPasswordStore.js
  src/stores/mapStore.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#123 [기능] 회원가입시 기본 이미지 추가
  src/components/AppStatusPage.jsx
  src/pages/Main/GymDetail/GymDetailHeader.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Map/Map.jsx
  src/stores/myPageStore.js
  src/stores/signStore.js
  src/utils/downloadImage.js
  src/utils/getPbImageURL.js
  src/utils/index.js
Labels: 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#126 [기능] 필터 기능 리팩토링 / 현재위치 메인페이지에 보여주는 기능
  src/pages/Main/FilterList.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/MapLink.jsx
  src/stores/mainStore.js
  src/stores/mapStore.js
Labels: ⚛️ React, 🎗️ Javascript, 🎀 CSS, 🛠️ Refactor

#127 [수정] 헬스장 디테일 페이지 렌더링 오류 해결
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/GymDetail/Refundpolicy.jsx
  src/pages/Main/GymDetail/TrainerList.jsx
  src/pages/Main/Payment/Payment.jsx
  src/pages/Main/TrainerDetail/TrainerDetail.jsx
  src/router.jsx
Labels: 🐞 Bug, 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#129 [기능] 헬스장 찜 목록 보여주기 / 현재위치 기반 헬스장 서비스 구현
  index.html
  src/components/AppStatusPage.jsx
  src/layouts/RootLayout.jsx
  src/main.jsx
  src/pages/Error.jsx
  src/pages/Main/FilterList.jsx
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/GymDetail/Refundpolicy.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/MyPage/WishList/WishList.jsx
  src/router.jsx
  src/stores/mainStore.js
  src/stores/mapStore.js
  src/utils/geocodeAddress.js
  src/utils/index.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🎀 CSS, 🛠️ Refactor

#130 [수정] 머지 오류 해결
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/GymDetail/Refundpolicy.jsx
  src/pages/Main/GymDetail/TrainerList.jsx
Labels: 🐞 Bug

#133 [기능] 헬스장 찜 기능
  src/components/AppList.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/MyPage/WishList/WishList.jsx
  src/stores/mainStore.js
  src/stores/mapStore.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🎀 CSS

#136 [기능] 헬스장 검색 기능 재구현
  src/components/AppList.jsx
  src/components/index.js
  src/pages/Main/Filter/HealthPrice.jsx
  src/pages/Main/FilterList.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/MapLink.jsx
  src/pages/MyPage/WishList/WishList.jsx
  src/stores/mainStore.js
  src/stores/mapStore.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#134 [오류] myCoupon/ EditNickname 키보드 탭 했을시 active만 나오는 오류/ 포켓호스트 연동 오류
  src/pages/MyPage/EditProfile/EditNickname.jsx
  src/pages/MyPage/EditProfile/EditNumber.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/MyProfile.jsx
  src/stores/myPageStore.js
  src/styles/_pagination.css
  src/styles/main.css
Labels: 🐞 Bug, 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#138 Feature/mypage
  package.json
  pnpm-lock.yaml
  public/assets/sprite.svg
Labels: 🦴 Markup, 🎀 CSS

#140 [수정] 위치 변경할때 스피너 나오는 기능 및 오류 수정
  src/components/AppList.jsx
  src/pages/Home.jsx
  src/pages/Main/FilterList.jsx
  src/pages/Main/GymList.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/SearchBar.jsx
  src/stores/mainStore.js
  src/stores/mapStore.js
  src/utils/getUserLocation.js
  src/utils/index.js
Labels: ⚛️ React, 🎗️ Javascript, 🛠️ Refactor

#142 [기능/추가/환경설정] MyPage/EditProfile/EditNickName.jsx
  src/pages/MyPage/EditProfile/EditNickname.jsx
  src/pages/MyPage/EditProfile/EditProfile.jsx
  src/stores/myPageStore.js
  vite.config.js
Labels: 📖 Documentation, 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS, 🏗️ Environment

#144 [수정] GymDetail 접근성 강화 및 성능 강화
  src/pages/Main/GymDetail/GymDetail.jsx
  src/stores/mainStore.js
  src/utils/getQueryString.js
  src/utils/index.js
Labels: ⚛️ React, 🎗️ Javascript, 👻 Pocketbase, 🛠️ Refactor

#146 [마크업/스타일링] 결제페이지 컴포넌트
  src/components/AppAccordion.jsx
  src/components/index.js
  src/constant.js
  src/hooks/usePriceData.js
  src/pages/Home.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/Payment/Payment.jsx
  src/pages/Main/Price/Price.jsx
  src/pages/Main/Price/PriceList.jsx
  src/pages/Main/SearchBar.jsx
  src/router.jsx
  src/stores/priceListStore.js
Labels: ⚛️ React, 🎗️ Javascript, 🛠️ Refactor

#148 [마크업, 스타일링, 기능] 헬스장 디테일페이지, 헬스장 리뷰 페이지 완료
  src/api/CRUD.js
  src/components/AppCheckboxInput.jsx
  src/components/AppImageDisplay.jsx
  src/components/AppReviewList.jsx
  src/components/index.js
  src/pages/Main/GymDetail/AmenitiesList.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/GymDetailHeader.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/GymDetail/TrainerList.jsx
  src/pages/Main/Review/Review.jsx
  src/pages/Main/TrainerDetail/TrainerDetail.jsx
  src/router.jsx
  src/stores/mainStore.js
  src/utils/formatDate.js
  src/utils/index.js
  tailwind.config.js
Labels: 🐞 Bug, 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#151 [마크업/수정] 마이페이지 설정/ 리뷰 관리 페이지 구현, 리뷰 컴포넌트 수정
  src/components/AppReviewList.jsx
  src/pages/Main/Review/Review.jsx
  src/pages/Main/TrainerDetail/TrainerDetail.jsx
  src/pages/MyPage/ReviewSettings/ReviewSettings.jsx
  src/stores/myPageStore.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#153 [기능] 금액 선택리스트 세부 기능 구현
  src/components/AppCheckboxInput.jsx
  src/components/AppStatusPage.jsx
  src/pages/Main/Price/Price.jsx
  src/pages/Main/Price/PriceList.jsx
  src/stores/priceListStore.js
Labels: ⚛️ React, 🎗️ Javascript, 🛠️ Refactor

#155 PaymentHistory/PaymentList 생성 및 기능
  src/pages/MyPage/EditProfile/EditEmail.jsx
  src/pages/MyPage/EditProfile/EditNickname.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/PaymentHistory/PaymentHistory.jsx
  src/pages/MyPage/PaymentHistory/PaymentList.jsx
  src/pages/MyPage/ReviewSettings/EditReview.jsx
  src/pages/MyPage/ReviewSettings/WriteReview.jsx
  src/stores/myPageStore.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#157 [수정] paymentHistory 생성시에 이미지 같이 전달
  src/pages/Main/Price/Price.jsx
  src/stores/priceListStore.js
Labels: ⚛️ React, 🎗️ Javascript, 🛠️ Refactor

#158 [수정/추가] PaymentList.jsx/MyCoupon.jsx/priceListStore에 일수 계산하는 함수 추가
  src/pages/MyPage/EditProfile/EditEmail.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/PaymentHistory/PaymentList.jsx
  src/stores/myPageStore.js
  src/stores/priceListStore.js
Labels: ⚛️ React, 🎗️ Javascript, 🎀 CSS

#160 [마크업/스타일링/기능] 트레이너 상세 정보 페이지
  src/components/AppImageDisplay.jsx
  src/components/AppReviewList.jsx
  src/components/AppTrainerProfile.jsx
  src/components/index.js
  src/pages/Main/GymDetail/TrainerList.jsx
  src/pages/Main/Review/Review.jsx
  src/pages/Main/TrainerDetail/TrainerDetail.jsx
  src/pages/MyPage/ReviewSettings/ReviewSettings.jsx
  src/router.jsx
  src/stores/mainStore.js
Labels: 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#163 [기능] 현재 위치 수정 및 map반영 현재위치 선택위치 검색위치 각각 나오게 필터링
  src/components/AppAccordion.jsx
  src/components/AppImageDisplay.jsx
  src/hooks/usePriceData.js
  src/pages/Main/FilterList.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/GymDetailHeader.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/GymDetail/Refundpolicy.jsx
  src/pages/Main/GymDetail/TrainerList.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/Price/PriceList.jsx
  src/stores/mainStore.js
  src/stores/mapStore.js
  src/stores/priceListStore.js
Labels: ⚛️ React, 🎗️ Javascript, 🛠️ Refactor

#165 [마크업/스타일링/수정] 트레이너 디테일 페이지 오류 해결, 리뷰 메뉴 모달창 마크업
  src/components/AppReviewList.jsx
  src/components/AppReviewMenuModal.jsx
  src/components/index.js
  src/pages/Main/TrainerDetail/TrainerDetail.jsx
Labels: 🐞 Bug, 🦴 Markup, ⚛️ React, 🎗️ Javascript, 🎀 CSS

#167 [수정] 버그수정
  src/components/AppImageDisplay.jsx
  src/components/AppStatusPage.jsx
  src/pages/Signup/AgreementTerms.jsx
  src/utils/getPbImageURL.js
Labels: 🐞 Bug

#169 [버그] 버그수정
  src/components/AppHeader.jsx
  src/components/AppStatusPage.jsx
  src/pages/Login/Login.jsx
  src/utils/getPbImageURL.js
Labels: 🐞 Bug

#170 [수정] 배포에러 수정
  netlify.toml
Labels: 🐞 Bug

#172 [완료]Home.jsx 이미지 변경
  public/assets/bg.avif
  public/assets/home.png
  src/pages/Home.jsx
  src/pages/MyPage/EditProfile/EditProfile.jsx
Labels: 🎀 CSS

#174 [버그] 네비게이션 버그 수정
  README.md
  home.png
  image.png
  src/components/AppHeader.jsx
  src/main.jsx
  src/pages/Login/AuthLinks.jsx
  src/pages/Login/FindId/FindId.jsx
  src/pages/Login/FindPassword/FindPassword.jsx
  src/pages/Main/FilterList.jsx
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/WishList/WishList.jsx
Labels: 🐞 Bug

#178 [버그] 버그수정
  src/components/AppHeader.jsx
  src/main.jsx
  src/pages/Main/FilterList.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/PaymentHistory/PaymentList.jsx
Labels: 🐞 Bug

#181 [리팩토링] 성능개선
  README.md
  robots.txt
  src/components/AppAuthMessage.jsx
  src/components/AppList.jsx
  src/components/AppLoading.jsx
  src/components/AppNavLink.jsx
  src/router.jsx
Labels: 🛠️ Refactor

#182 [수정] strictMode 적용
  README.md
  src/main.jsx
Labels: ⚛️ React

#185 [리팩토링] 성능개선
  index.html
  src/components/AppImageDisplay.jsx
  src/components/AppTrainerProfile.jsx
  src/main.jsx
  src/pages/Chat/ChatSubmitForm.jsx
  src/pages/Chat/SwipeableChatRoom.jsx
  src/pages/Chat/SwipeableMessage.jsx
  src/pages/Login/FindPassword/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/Main/GymDetail/GymDetailFooter.jsx
  src/pages/Main/GymDetail/TrainerList.jsx
  src/pages/Main/Map/Map.jsx
  src/pages/Main/Price/Price.jsx
  src/pages/Main/Price/PriceList.jsx
  src/pages/Main/TrainerDetail/TrainerDetail.jsx
  src/pages/MyPage/EditProfile/EditImage.jsx
  src/pages/MyPage/MyCoupon.jsx
  src/pages/MyPage/MyProfile.jsx
Labels: 🛠️ Refactor

#186 [문서] README 작성
  README.md
Labels: 📖 Documentation

#188 [리팩토링] 코드 리팩토링
  src/main.jsx
  src/stores/mainStore.js
  src/stores/mapStore.js
Labels: 🛠️ Refactor

#189 [문서/코드 리팩토링] README 작성 / 코드 리팩토링
  README.md
  src/pages/Login/FindId/FindId.jsx
  src/stores/mainStore.js
Labels: 📖 Documentation, 🛠️ Refactor

#191 [리팩토링] 코드 리팩토링
  src/layouts/RootLayout.jsx
Labels: 🛠️ Refactor

#192 [문서] readme 업데이트
  README.md
Labels: 📖 Documentation

#195 [리팩토링] 자동스크롤 및 vite:preloadError 수정
  src/App.jsx
  src/components/AppStatusPage.jsx
  src/layouts/RootLayout.jsx
  src/pages/Chat/ChatRoomList.jsx
  src/pages/Login/FindId/FindId.jsx
  src/pages/Main/GymDetail/GymDetail.jsx
  src/pages/Main/GymDetail/LocationMap.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map/Map.jsx
  src/stores/findPasswordStore.js
  src/stores/mainStore.js
Labels: 🛠️ Refactor

#197 [수정] chatRooList 구독 에러 해결
  src/pages/Chat/ChatRoomList.jsx
Labels: 🐞 Bug
